// This is a skeleton starter React component generated by structo.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { StructoRandomDynamicPageButton } from "./structo/create_structo_app/StructoRandomDynamicPageButton";

function RandomDynamicPageButton(props) {
  
  return <StructoRandomDynamicPageButton {...props} />;
}

export default RandomDynamicPageButton;
