// This is a skeleton starter React page generated by structo.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@structoapp/react-web/lib/host";

import {
  StructoHomepage,
  StructoHomepage__HeadOptions
} from "../components/structo/create_structo_app/StructoHomepage";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [...StructoHomepage__HeadOptions.meta],
    links: [...StructoHomepage__HeadOptions.links]
  }),
  component: Homepage
});

function Homepage() {
  

  return (
    <PageParamsProvider__
      route={Route.fullPath}
      params={Route.useParams()}
      query={Route.useSearch()}
    >
      <StructoHomepage />
    </PageParamsProvider__>
  );
}

export default Homepage;
