// This is a skeleton starter React component generated by structo.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  StructoHomepage,
  //@ts-ignore
  DefaultHomepageProps
} from "./structo/create_structo_app/StructoHomepage";
import { HTMLElementRefOf } from "@structoapp/react-web";


export interface HomepageProps extends DefaultHomepageProps {}

function Homepage_(props: HomepageProps, ref: HTMLElementRefOf<"div">) {
 

  return <StructoHomepage root={{ ref }} {...props} />;
}

const Homepage = React.forwardRef(Homepage_);
export default Homepage;
