// This is a skeleton starter React component generated by structo.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  StructoRandomDynamicPageButton,
  DefaultRandomDynamicPageButtonProps
} from "./structo/create_structo_app/StructoRandomDynamicPageButton";


export interface RandomDynamicPageButtonProps
  extends DefaultRandomDynamicPageButtonProps {}

function RandomDynamicPageButton(props: RandomDynamicPageButtonProps) {
  
  return <StructoRandomDynamicPageButton {...props} />;
}

export default RandomDynamicPageButton;
