// This is a skeleton starter React page generated by structo.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@structoapp/react-web/lib/host";

import {
  StructoDynamicPage,
  StructoDynamicPage__HeadOptions
} from "../../../components/structo/create_structo_app/StructoDynamicPage";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/dynamic/$slug/")({
  head: () => ({
    meta: [...StructoDynamicPage__HeadOptions.meta],
    links: [...StructoDynamicPage__HeadOptions.links]
  }),
  component: DynamicPage
});

function DynamicPage() {
 

  return (
    <PageParamsProvider__
      route={Route.fullPath}
      params={Route.useParams()}
      query={Route.useSearch()}
    >
      <StructoDynamicPage />
    </PageParamsProvider__>
  );
}

export default DynamicPage;
