// This is a skeleton starter React page generated by structo.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@structoapp/react-web/lib/host";
import {
  StructoHomepage,
  Head
} from "../components/structo/create_structo_app/StructoHomepage";

export { Head };

function Homepage({ location, path, params }) {
  
  return (
    <PageParamsProvider__
      route={path}
      params={params}
      query={Object.fromEntries(new URLSearchParams(location.search))}
    >
      <StructoHomepage />
    </PageParamsProvider__>
  );
}

export default Homepage;
