// This is a skeleton starter React component generated by structo.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { StructoDynamicPage } from "./structo/create_structo_app/StructoDynamicPage";

function DynamicPage_(props, ref) {

  return <StructoDynamicPage root={{ ref }} {...props} />;
}

const DynamicPage = React.forwardRef(DynamicPage_);

export default DynamicPage;
