// This is a skeleton starter React component generated by structo.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { StructoHomepage } from "./structo/create_structo_app/StructoHomepage";

function Homepage_(props, ref) {
 
  return <StructoHomepage root={{ ref }} {...props} />;
}

const Homepage = React.forwardRef(Homepage_);

export default Homepage;
